name: Automatic Deploy to Vercel and comment

on:
  push:
    branches:
      - main
      - preview
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Preview
        if: github.ref == 'refs/heads/preview'
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          # Capture the preview URL
          PREVIEW_URL=$(vercel --json | jq -r '.[0].url')
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} --confirm yes

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(echo "${{ github.event.ref }}" | awk -F/ '{print $3}')
          COMMENT="Preview deployment: [Preview Link](${PREVIEW_URL})"
        env:
          PREVIEW_URL: ${{ steps.deploy.outputs.PREVIEW_URL }}
