name: Automatic Deploy to Vercel

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Get PR Number
        id: get_pr
        run: |
          # Get the pull request number associated with the commit
          PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            | jq -r '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Post Comment on Pull Request
        if: env.PR_NUMBER != 'null'
        run: |
          COMMENT_BODY=$(jq -n --arg body "deploy done" '{body: $body}')
          curl -s -L -X POST \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/comments"
