name: Automatic Deploy to Vercel

on:
  push:
    branches:
      - main
      - Create-yml-for-vercel-Deploy
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Preview
        if: github.ref == 'refs/heads/Create-yml-for-vercel-Deploy'
        run: |
          DEPLOY_OUTPUT=$(vercel --prod=false --confirm --token ${{ secrets.VERCEL_TOKEN }})
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*')
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        run: |
          DEPLOY_OUTPUT=$(vercel --prod=false --token ${{ secrets.VERCEL_TOKEN }} --confirm)
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*')
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/prod'
        run: |
          DEPLOY_OUTPUT=$(vercel --prod=true --token ${{ secrets.VERCEL_TOKEN }} --confirm)
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*')
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment on Pull Request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_URL=${{ env.PREVIEW_URL }}
          COMMENT="Preview deployment: [Preview Link](${PREVIEW_URL})"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d "{\"body\":\"$COMMENT\"}" \
               -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
