name: Automatic Deploy to Vercel

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Preview
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod'
        run: |
          DEPLOY_OUTPUT=$(vercel --prod=false --confirm --token ${{ secrets.VERCEL_TOKEN }})
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*')
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Get Pull Request Number
        id: get_pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Display PR Number
        run: echo "Pull Request Number is $PR_NUMBER"

      - name: Post Comment on Pull Request
        if: github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod'
        run: |
          PR_NUMBER=$(echo "${GITHUB_REF#refs/heads/}")
          PREVIEW_URL=${{ env.PREVIEW_URL }}
          COMMENT_BODY='{"body":"Preview deployment: [Preview Link]('${PREVIEW_URL}')"}'
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -d "$COMMENT_BODY" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
