name: Automatic Deploy to Vercel

on:
  push:
    branches:
      - main
      - Create-yml-for-vercel-Deploy
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Preview
        if: github.ref == 'refs/heads/Create-yml-for-vercel-Deploy'
        run: |
          vercel --prod=false --token ${{ secrets.VERCEL_TOKEN }} --confirm 
          PREVIEW_URL=$(vercel ls --token ${{ secrets.VERCEL_TOKEN }} | awk '{print $2}')
          echo "::set-output name=PREVIEW_URL::$PREVIEW_URL"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        run: |
          vercel --prod=false --token ${{ secrets.VERCEL_TOKEN }} --confirm
          PREVIEW_URL=$(vercel ls --token ${{ secrets.VERCEL_TOKEN }} | awk '{print $2}')
          echo "::set-output name=PREVIEW_URL::$PREVIEW_URL"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/prod'
        run: |
          vercel --prod=true --token ${{ secrets.VERCEL_TOKEN }} --confirm
          PREVIEW_URL=$(vercel ls --token ${{ secrets.VERCEL_TOKEN }} | awk '{print $2}')
          echo "::set-output name=PREVIEW_URL::$PREVIEW_URL"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment on Pull Request
        if: success() && startsWith(github.ref, 'refs/pull/')
        run: |
          PR_URL=${{ github.event.pull_request.url }}
          PREVIEW_URL=${{ steps.deploy.outputs.PREVIEW_URL }}
          COMMENT="Preview deployment: [Preview Link](${PREVIEW_URL})"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$COMMENT\"}" -X POST "$PR_URL/comments"
