name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add a comment to the pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github } = require('@actions/github');

            // Customize your comment message here
            const message = "Thank you for your pull request! We will review it soon.";

            await github.issues.createComment({
              ...github.context.repo,
              issue_number: github.context.issue.number,
              body: message
            });
